API_KEY = ''  # started parameters: vk key
VERSION =   # version of api
GROUP_DOMAIN = ''  # group for parsing
COUNT = 100  # quantity of posts
OFFSET = 0
DATABASE = ""
TG_TOKEN = ""
LOG = ''
TARGETCHAT = 
